services:
  - type: web
    name: map-app-live
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: |
      cd server && npm install &&
      cd ../client && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.11.0"
